### PR TITLE
Replace mode annotation in propers tool

### PR DESCRIPTION
**Pull request by Kljunas2**
Mode annotation when using psalm toned propers was incorrect if the mode has beend changed.

### CODE REVIEW

**Comment by bbloomf** [comment]
This should be fixed now

**Comment by Kljunas2** [comment]
Neither github.io page nor fresh git clone do not show proper tones in annotations. Is there something I am missing?
In the image, I have chosen the third mode for introitus, melody is correct, while annotation still says VII.
image

**Comment by bbloomf** [comment]
I forgot to push my commit.  It should be up there now.

Sorry!

**Comment by Kljunas2** [comment]
It works now, thanks.

**Pull request closed without merging**
